[versions]
compose-multiplatform = "1.9.0"

kotlin = "2.1.20"
agp = "8.10.1"

androidx-activityCompose = "1.11.0"
jetbrains-lifecycle = "2.9.3"
androidx-room = "2.8.0"
androidx-navigation = "2.9.0"
sqlite = "2.6.0"
coil = "3.3.0"
ktor = "3.3.0"
kotlinx-coroutines = "1.10.1"
kotlinx-immutableCollections = "0.4.0" # https://github.com/Kotlin/kotlinx.collections.immutable/releases
ksp = "2.1.20-2.0.0"

calf = "0.8.0"
mupdfFitz = "1.25.1"
mupdfFitzAar = "1.26.5"
mmkv = "2.2.3"
mmkv-kotlin = "1.3.0"
core = "1.17.0"
lifecycleViewmodelComposeAndroid = "2.9.3"
tiff-loader = "1.1.4"
jsoup = "1.21.2"
crashreport = "4.1.9.3"
reorderable = "3.0.0"
sonner = "0.3.8"
xmlutil = "0.90.3"
klock = "4.0.3"

android-compileSdk = "36"
android-minSdk = "24"
android-targetSdk = "35"

versionCode = "10"
versionName = "1.2.0"

[libraries]
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }

androidx-navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "androidx-navigation" }

filePicker = { module = "com.mohamedrejeb.calf:calf-file-picker", version.ref = "calf" }
mupdf-fitz = { module = "com.artifex.mupdf:mupdf-fitz", version.ref = "mupdfFitz" }
mupdf-fitz-aar = { module = "com.artifex.mupdf:mupdf-fitz", version.ref = "mupdfFitzAar" }

androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "androidx-room" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "androidx-room" }
sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqlite" }

jetbrains-lifecycle-viewmodel-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "jetbrains-lifecycle" }
jetbrains-lifecycle-viewmodel = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "jetbrains-lifecycle" }
jetbrains-lifecycle-runtime-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "jetbrains-lifecycle" }
androidx-lifecycle-viewmodel-compose-android = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose-android", version.ref = "lifecycleViewmodelComposeAndroid" }
kotlinx-coroutines-swing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-immutableCollections = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinx-immutableCollections" }

ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }

xmlutil-core = { module = "io.github.pdvrieze.xmlutil:core", version.ref = "xmlutil" }
klock = { module = "com.soywiz.korlibs.klock:klock", version.ref = "klock" }

mmkv = { module = "com.tencent:mmkv", version.ref = "mmkv" }
mmkv-kotlin = { module = "com.ctrip.flight.mmkv:mmkv-kotlin", version.ref = "mmkv-kotlin" }
mmkv-kotlin-android = { module = "com.ctrip.flight.mmkv:mmkv-kotlin-android", version.ref = "mmkv-kotlin" }
mmkv-kotlin-macosx64 = { module = "com.ctrip.flight.mmkv:mmkv-kotlin-macosx64", version.ref = "mmkv-kotlin" }
mmkv-kotlin-macosarm64 = { module = "com.ctrip.flight.mmkv:mmkv-kotlin-android", version.ref = "mmkv-kotlin" }

coil-kt = { group = "io.coil-kt.coil3", name = "coil", version.ref = "coil" }
coil-kt-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
coil-kt-okhttp = { group = "io.coil-kt.coil3", name = "coil-network-okhttp", version.ref = "coil" }
coil-kt-ktor3 = { group = "io.coil-kt.coil3", name = "coil-network-ktor3", version.ref = "coil" }
androidx-core = { group = "androidx.core", name = "core", version.ref = "core" }
tiff-loader = { module = "com.archko.reader.image:library-android", version.ref = "tiff-loader" }
tiff-loader-jar = { module = "com.archko.reader.image:tiff-desktop", version.ref = "tiff-loader" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
reorderable = { module = "sh.calvin.reorderable:reorderable", version.ref = "reorderable" }

sonner = { module = "io.github.dokar3:sonner", version.ref = "sonner" }
crashreport = { module = "com.tencent.bugly:crashreport", version.ref = "crashreport" }

[plugins]
#kotlin-native-cocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
kotlinxSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

# Android
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
androidKmpLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
room = { id = "androidx.room", version.ref = "androidx-room" }